title = "Polarity"
# The URL the site will be built for
base_url = "https://polarity-lang.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "juice"

[markdown]
[markdown.highlighting]
light_theme = "github-light-default"
dark_theme = "github-dark-default"

[extra]
juice_logo_name = "Polarity"
juice_logo_path = "logo_transparent.svg"
juice_extra_menu = [
    { title = "Github", link = "https://github.com/polarity-lang/polarity"}
]
juice_exclude_menu = [
    "exclude_from_nav"
]
repository_url = "https://github.com/polarity-lang/polarity-lang.github.io"
